// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAnlBVHHDQKueMrxbLrzeH4ihHb6Uul88',
    appId: '1:437403925289:web:7f1929cdb2f8320f375538',
    messagingSenderId: '437403925289',
    projectId: 'trkd-12728',
    authDomain: 'trkd-12728.firebaseapp.com',
    databaseURL: 'https://trkd-12728-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trkd-12728.firebasestorage.app',
    measurementId: 'G-C7VZ768FMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN2LmBbgTm6omCLKB6vGpgEtRwGhnS4RA',
    appId: '1:437403925289:android:fc951c792a4f546d375538',
    messagingSenderId: '437403925289',
    projectId: 'trkd-12728',
    databaseURL: 'https://trkd-12728-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trkd-12728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNusjeTsDiE9WiPVYqYYxnf8v8LFYozso',
    appId: '1:437403925289:ios:908633f8ecc11545375538',
    messagingSenderId: '437403925289',
    projectId: 'trkd-12728',
    databaseURL: 'https://trkd-12728-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trkd-12728.firebasestorage.app',
    androidClientId: '437403925289-40uc9cas9its6m8mstuoqt9dt98dl9h2.apps.googleusercontent.com',
    iosClientId: '437403925289-b1o561iqsfki75bjddnv6hnugtd28mtb.apps.googleusercontent.com',
    iosBundleId: 'com.healthapp.mvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNusjeTsDiE9WiPVYqYYxnf8v8LFYozso',
    appId: '1:437403925289:ios:908633f8ecc11545375538',
    messagingSenderId: '437403925289',
    projectId: 'trkd-12728',
    databaseURL: 'https://trkd-12728-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trkd-12728.firebasestorage.app',
    androidClientId: '437403925289-40uc9cas9its6m8mstuoqt9dt98dl9h2.apps.googleusercontent.com',
    iosClientId: '437403925289-b1o561iqsfki75bjddnv6hnugtd28mtb.apps.googleusercontent.com',
    iosBundleId: 'com.healthapp.mvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAnlBVHHDQKueMrxbLrzeH4ihHb6Uul88',
    appId: '1:437403925289:web:a345d2be43fb5964375538',
    messagingSenderId: '437403925289',
    projectId: 'trkd-12728',
    authDomain: 'trkd-12728.firebaseapp.com',
    databaseURL: 'https://trkd-12728-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trkd-12728.firebasestorage.app',
    measurementId: 'G-0JGN7RKF5N',
  );
}
